version: '3'
services:
  mongo:
    container_name: mongo
    restart: always
    image: jshamoo/cp-mongo
    ports:
      - '27017:27017'

  webapp:
    container_name: castphotos
    restart: always
    image: jshamoo/cp-webapp
    environment:
      - MONGODB_URL=mongodb://mongo:27017/castphotos
      - PORT=80
    ports:
      - '80:80'
    links:
      - mongo
